query fetchDirectorWithID($id: Int!) {
  authorized {
    director(id: $id) {
      directorId
      name
      age
      movies {
        id
        title
        description
        year
        directorId
        likes
      }
    }
  }
}
